name: Publish Release

on:
  release:
    types: [released]

env:
  MAVEN_SNAPSHOT: false

jobs:
  publish:
    name: Publish release build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Decrypt secrets
        run: scripts/decrypt-secrets.sh "${{ secrets.SECRETS_PASSPHRASE }}"

      - name: Build project
        run: ./gradlew clean :composenav:assembleRelease

      - name: Publish to MavenCentral
        run: ./gradlew publishReleasePublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository --max-workers 1

      - name: Clean up secrets
        if: always()
        run: scripts/cleanup-secrets.sh
