name: Publish Release

on:
  release:
    types: [released]

jobs:
  publish:
    name: Publish release build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Decrypt secrets
        run: scripts/decrypt-secrets.sh "${{ secrets.SECRETS_PASSPHRASE }}"

      - name: Release project
        run: ./gradlew assembleRelease

      - name: Create source jar
        run: ./gradlew androidSourcesJar

      - name: Publish to MavenCentral
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          MAVEN_SNAPSHOT: false

      - name: Clean up secrets
        if: always()
        run: scripts/cleanup-secrets.sh
