name: "Publish snapshot"

on:
  push:
    branches:
      - develop

jobs:
  snapshot-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Decrypt secrets
        run: scripts/decrypt-secrets.sh "${{ secrets.SECRETS_PASSPHRASE }}"

      - name: Build project
        run: ./gradlew clean assembleRelease

      - name: Create source jar
        run: ./gradlew androidSourcesJar

      - name: Publish to MavenCentral
        run: ./gradlew publishReleasePublicationToSonatypeRepository
        env:
          MAVEN_SNAPSHOT: true

      - name: Clean up secrets
        if: always()
        run: scripts/cleanup-secrets.sh
