name: "Pull request build"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: "Tests and code analysis"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Danger Checks
        run: |
          ./gradlew dependencyUpdates -DoutputDir=build/danger
          bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: testDebugUnitTest

      - name: Run static analysis
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ktlintCheck detekt
